// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGuie5_fiX6TQDE78MRFzAo2YulVsXPVY',
    appId: '1:598249401978:web:b1e5d67b4204e2f98395c3',
    messagingSenderId: '598249401978',
    projectId: 'llapp-notes',
    authDomain: 'llapp-notes.firebaseapp.com',
    storageBucket: 'llapp-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Yx_r3HdJM35KDtrkXcRcE1wHLkA4mZ4',
    appId: '1:598249401978:android:84cdad7bf5908af38395c3',
    messagingSenderId: '598249401978',
    projectId: 'llapp-notes',
    storageBucket: 'llapp-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0uF-qG32WnGCeUWiQEfqhgwzhlxfowZU',
    appId: '1:598249401978:ios:a4d121fe4528ef3f8395c3',
    messagingSenderId: '598249401978',
    projectId: 'llapp-notes',
    storageBucket: 'llapp-notes.appspot.com',
    iosBundleId: 'com.example.llapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0uF-qG32WnGCeUWiQEfqhgwzhlxfowZU',
    appId: '1:598249401978:ios:c65891b3cecca8488395c3',
    messagingSenderId: '598249401978',
    projectId: 'llapp-notes',
    storageBucket: 'llapp-notes.appspot.com',
    iosBundleId: 'com.example.llapp.RunnerTests',
  );
}
